@path=/api
@route={{url}}{{port}}{{path}} 
GET {{route}}/signup HTTP/1.1

### 
# Posting User For Signup
POST {{route}}/signup HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "email": "smithjohn@example.com",
  "password": "smithJone"
}

###
# Signing In User
POST {{route}}/signin HTTP/1.1
Content-Type: application/json

{ 
  "email": "smithjohn@example.com",
  "password": "smithJone"
}

### 
# signout
GET {{route}}/signout HTTP/1.1